### ISSUE TITLE
v.2.0.0 Alpha 1 / Archi 4.5 Beta 1 error

### ISSUE THREAD

**Issue by jmariani** [archi-contribs/specialization-plugin#37] opened 2019-06-24 21:46 UTC
Error while clicking on the "Specialization" tab. Log attached.

[SpecializationPlugin.log](https://github.com/archi-contribs/specialization-plugin/files/3322695/SpecializationPlugin.log)

**Comment by herve91** [comment] 2019-06-25 07:48
Hi Jorge,

Thanks for rising this issue, I know what happens. It will be solved in the next release.

Best regards
Hervé

**Comment by jmariani** [comment] 2019-06-27 16:58
Super! Same happens with Archi 4.4

**Comment by herve91** [comment] 2019-06-28 06:48
Hi Jorge,

Yes as the issue is not linked to Archi but to my plugin. So the error message will be raise whetever the Archi version.

Best regards
Hervé

**Comment by chdessus** [comment] 2019-07-03 06:49
Hello, 
I get the error message when using SPECIALIZATION : 

An error has occurred. See error log for more details.
java.lang.NullPointerException

Seams to be the same as above.
--------------------------------------------------------------------------
Version of Archi, Operating System
VERSION 4.4, last download and install on the 2d of july

Behaviour
I have installed the SPECIALIZATION plugin. I get an error message in ARCHI when I click on it :
An error has occurred. See error log for more details.
java.lang.NullPointerException

Steps to Reproduce the Behaviour
open ARCHI
Select a view
Select an object on the view, In the properperties, you can see Specialization and Drill down
Click on DRILL DOWN : it works perfectly
Click on SPECIALIZATION, you get the error message "An error has occurred. See error log for more details. java.lang.NullPointerException"

---------------------------------------------
Regards

have a nice day.

**Comment by herve91** [comment] 2019-07-03 19:14
fixed in next release

**Closed by herve91** 2019-07-03 19:14 UTC
Labels: bug
