### ISSUE TITLE
Magic Connector not working

### ISSUE THREAD

**Issue by Phillipus** [archi-contribs/specialization-plugin#25] opened 2019-03-22 09:21 UTC
Hi Herve, with this plugin installed the Magic Cursor is not working as it should do when clicking from a concept to white space.

See https://forum.archimatetool.com/index.php?topic=485.0

Windows/Mac/Linux.

**Comment by Phillipus** [comment] 2019-03-22 10:22
Also, when a diagram object has a (large) image as an icon, when dragging the magic connector from the object there seems to be a UI lag. Is there something running in the background on the UI thread? Or perhaps a mouse listener? Or Display#readAndDispatch() being called somewhere?

**Comment by rchevallier** [comment] 2019-03-22 10:59
Confirm behaviour issue on my computers with the plugin installed

**Comment by Phillipus** [comment] 2019-03-23 12:45
@herve91 Herve, I checked your code. It seems to be an easy fix.

SpecializationPlugin.java line 326 (`getFullName()` method) should check for null `obj`. You could also check for other possible null values in case there are more.

**Comment by Phillipus** [comment] 2019-03-23 13:13
A UIProvider is really providing UI info for an EClass, so does not always have an EObject instance. When it does, it's because the instance determines the icon or default size which can be different for each

**Comment by herve91** [comment] 2019-03-24 17:29
Thanks a lot for pointing this out.

I'll fix it ASAP ...

**Comment by Phillipus** [comment] 2019-03-24 17:31
Rather than just fixing the NPE, if you could make it so that UIProvider#instance is not accessed. Better to use the EClass as a key to get icons.

**Comment by Phillipus** [comment] 2019-03-24 17:46
> The problem you will have is with `SpecializationPlugin.mustReplaceIcon(this.instance)`

In your usage of that, you are trying to determine the context for the instance - whether it is in a folder, etc. I understand what you are trying to do, but the `instance` field shouldn't really be used for that. But I can't think of another way to get the instance in your code, as you are over-riding the UIProvider. So maybe best to just fix the NPE and one day there may be a better system for plugging into the UI via a different extension point.

**Comment by herve91** [comment] 2019-03-24 18:23
All right. If you think of a better way to achieve this, please do not hesitate :)

**Comment by Phillipus** [comment] 2019-03-24 18:26
Ideally, we need a plugin extension point so that plugins can provide information such as icon, size, color, label, figures etc for different contexts in response to the main Archi code's UIProviders. But that's not going to happen just yet.

**Comment by herve91** [comment] 2019-03-27 09:56
I'm puzzled because I fail to reproduce the issue on Windows with images 1920x1200. May be very specific to MAC :(

![image](https://user-images.githubusercontent.com/9281982/55066795-ce5fd880-507e-11e9-81a3-559a169f7818.png)

Anyway, checking for null values is always a good idea.

**Comment by Phillipus** [comment] 2019-03-27 09:58
Nit specific to Mac.

1. Select Magic Connector
2. Click on Element box
3. Click on white space on diagram, not another element

**Comment by herve91** [comment] 2019-03-27 10:15
Oh, never used this functionality ... So it fails also on Windows ...

Anyway, the fix is ready and I'll sbmit it today.

Thanks again :-)

**Comment by Phillipus** [comment] 2019-03-27 10:18
It's not OS specific. As I said, `UIProvider#instance` can be null as a UIProvider is providing UI information for a class rather than an instance. In future versions of Archi `instance` will be removed.

**Comment by herve91** [comment] 2019-03-27 10:19
Yes, I got it ...

**Comment by herve91** [comment] 2019-04-01 20:14
Fixed in release 1.0.11

**Closed by herve91** 2019-04-01 20:14 UTC
Labels: bug
