### ISSUE TITLE
Error message when adding a (new or existing) application component to a view

### ISSUE THREAD

**Issue by mikisvandijk** [archi-contribs/specialization-plugin#44] opened 2020-11-27 12:41 UTC
I use the specialisation plugin to show a name and a company-defined applicatio-number in the application component.
Bij setting the label expression "to ${name}\n${property:SW}"

Everytime I add a component to a view, I get an error message
"An error has occurred. See error log for more details.
org.archicontribs.specialization.uiProvider.elements.figures.ApplicationComponentFigure.setText()V"

It seems a warning, after acknowledging the message, everything seems working fine.

What information can I provide you to have a look at the issue?

**Comment by herve91** [comment] 2020-11-27 13:16
Hi,

You need to activate the plugin log file in trace mode through the preference page:
![image](https://user-images.githubusercontent.com/9281982/100452822-2f447d00-30ba-11eb-9fe2-96b1004a8eb7.png)

then you need to reproduce the error and provide me with the part of the log file that contains the Exception (and a few lines before, let say a 10ish, that I can understand what the plugin was doing when the exception happend.


Alternatively, you may use the new label functionality that is natively provided by Archi since version 4.7 as the developers included this part directly in their code:
![image](https://user-images.githubusercontent.com/9281982/100453393-2011ff00-30bb-11eb-8a35-d9cbb567737f.png)

Best regards
Hervé

**Comment by rich-biker** [comment] 2021-01-07 08:56
This has gone quiet. I'm also having this problem, Hervé, so I'll provide some more info. Of course, we could use the new labels feature, but I like to be able to replace icons on shapes when I specialise.

**Plugin**: /Applications/Archi.app/Contents/Eclipse/plugins/org.archicontribs.specialization_v1.0.11.jar
**Archi version**: 4.8.0 Build 202012140831 (although it's been happening before this).
**Mac OS**: Big Sur

**Message**:
`An error has occurred. See error log for more details.
'void org.archicontribs.specialization.uiProvider.elements.figures.ProcessFigure.setText()'`

Here's the snippet of trace log file

[SpecializationPlugin_7Jan_Trace.log](https://github.com/archi-contribs/specialization-plugin/files/5780469/SpecializationPlugin_7Jan_Trace.log)

**Comment by herve91** [comment] 2021-01-07 16:28
Hi,

Unfortunately, the log file you provided does not contain any error message, but it should have one (as per the message you've had on your screen).

I do not have any MacOS at the moment so I cannot reproduce your environment and do not have the same error on Windows.

I'll try to do more testing and in the meantime, please reproduce the error and check if there is an error message printed in the log file.

**Comment by rich-biker** [comment] 2021-01-07 18:16
There wasn't an error anywhere in the log, so don't worry. 
I've just realised that the 1.0.12.archiplugin was available and should be used - I was using an older 1.0.11.jar version.

This paved the way: https://github.com/archi-contribs/specialization-plugin/issues/50#issuecomment-756271794

Your latest code is just fine. I think you should close this.

**Comment by herve91** [comment] 2021-01-08 09:05
The lastest version of the plugin has effectively been recompiled against the latest version of Archi because the libraries were not aligned anymore.

So I close your this case.

Best regards

**Closed by herve91** 2021-01-08 09:05 UTC

**Comment by mikisvandijk** [comment] 2021-01-08 14:26
Excuse me that I didn't react sooner. 

But using the recompiled version of the plugin seems to solve the problem for me as well. 

Thanks and kind regards

**Comment by herve91** [comment] 2021-01-08 14:48
Great, happy to learn your issue is solved as well

Best regards
